# apiVersion: karpenter.k8s.aws/v1beta1
# kind: EC2NodeClass
# metadata:
#   name: "default"
# spec:
#   amiFamily: AmazonLinux2
#   instanceTypes:
#     - m5.large
#     - m5.medium
#   subnetSelector:
#     karpenter.sh/discovery: aknys
#   securityGroupSelector:
#     karpenter.sh/discovery: aknys
#   zoneSelector:
#     karpenter.sh/discovery: "true"
#   spotPricing:
#     maxPrice: 0.08
